version: 2

linters:
  disable:
    - errcheck
    - gosec
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

linters-settings:
  govet:
    enable:
      - shadow
  gosec:
    excludes:
      - G104 # Audit errors not checked (non-critical Excel formatting)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
